### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pawansingh333** [asish1346/NotPixelBot#1]
4xx Error during downloading image from https://fra1.digitaloceanspaces.com/notpix-user-content/templates/6624523270.png No retries will be attempted.
NotPixel | 2024-12-01 17:30:03 | WARNING  - 1985647434 | Paint attempt 5 failed. | Retrying in 10 sec | Client error 400 for URL: https://fra1.digitaloceanspaces.com/notpix-user-content/templates/6624523270.png
NotPixel | 2024-12-01 17:30:04 | ERROR    - 918126214501 | Maximum retry attempts reached. Ending painting process.

**Comment by asish1346** [comment]
@Pawansingh333 it's because of NotPixel Server was down that time
