### ISSUE TITLE
Allways Error 

### ISSUE THREAD

**Issue by Pawansingh333** [asish1346/NotPixelBot#4]
allways getting this error 
Failed to send tganalytics event, retrying in 5 seconds | Attempts: 1
Failed to send tganalytics event, retrying in 5 seconds | Attempts: 2
Failed to send tganalytics event, retrying in 5 seconds | Attempts: 3
Error while sending tganalytics event
Retrying in 600 seconds

AND AFTER 600 SECONDS REPETE SAME ERROR BOT NOT WORKING

**Comment by asish1346** [comment]
It's because of you haven't installed nodejs

**Comment by Pawansingh333** [comment]
im using node js

**Comment by asish1346** [comment]
Have you updated the bot?

**Comment by Pawansingh333** [comment]
yes
